#!/bin/sh -x
DIR=${1-$(date +%d)}
if test -d $DIR; then
  echo $DIR exists already
  exit
fi
NUM=${DIR#0}

# COOKIES="--no-cookies --header Cookie:\\ session=$(cat cookie)"
mkdir -p $DIR/ruby
cp 01/Makefile $DIR
echo "#!/usr/bin/env ruby" > $DIR/ruby/solution.rb

wget $COOKIES --output-document=$DIR/$NUM.html http://adventofcode.com/2016/day/$NUM
wget $COOKIES --output-document=$DIR/input.txt http://adventofcode.com/2016/day/$NUM/input
git add $DIR
