#!/bin/bash -x
DIR=${1-$(date +%d)}
if test -d $DIR; then
  echo $DIR exists already
#  exit
fi
NUM=${DIR#0}

COOKIES=(--no-cookies --header "Cookie: session=$(cat cookie)")
mkdir -p "$DIR"/ruby
cp 01/Makefile "$DIR"
if [ ! -f "$DIR"/ruby/solution.rb ]; then
    echo "#!/usr/bin/env ruby" > "$DIR"/ruby/solution.rb
fi

YEAR="$(basename $(dirname $(realpath "$0")))"
wget "${COOKIES[@]}" --output-document="$DIR"/"$NUM".html https://adventofcode.com/"$YEAR"/day/"$NUM"
wget "${COOKIES[@]}" --output-document="$DIR"/input.txt https://adventofcode.com/"$YEAR"/day/"$NUM"/input
git add "$DIR"
