[package]
name = "04_the_ideal_stocking_stuffer"
version = "0.1.0"
authors = ["Martin Vidner <martin@vidner.net>"]

[[bin]]
name = "04_the_ideal_stocking_stuffer"

[dependencies]
rust-crypto = "0.2.35"
